src/Entity/Utente.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UtenteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=UtenteRepository::class)
 */
class Utente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nome;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cognome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Soprannome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Indirizzo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Citta;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Provincia;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Stato;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CodiceFiscale;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Telefono1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Telefono2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CodiceUtente;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $Nota;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $Nota1;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $Nota2;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $Nota3;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->Nome;
    }

    public function setNome(string $Nome): self
    {
        $this->Nome = $Nome;

        return $this;
    }

    public function getCognome(): ?string
    {
        return $this->Cognome;
    }

    public function setCognome(string $Cognome): self
    {
        $this->Cognome = $Cognome;

        return $this;
    }

    public function getSoprannome(): ?string
    {
        return $this->Soprannome;
    }

    public function setSoprannome(?string $Soprannome): self
    {
        $this->Soprannome = $Soprannome;

        return $this;
    }

    public function getIndirizzo(): ?string
    {
        return $this->Indirizzo;
    }

    public function setIndirizzo(?string $Indirizzo): self
    {
        $this->Indirizzo = $Indirizzo;

        return $this;
    }

    public function getCitta(): ?string
    {
        return $this->Citta;
    }

    public function setCitta(?string $Citta): self
    {
        $this->Citta = $Citta;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->Provincia;
    }

    public function setProvincia(?string $Provincia): self
    {
        $this->Provincia = $Provincia;

        return $this;
    }

    public function getStato(): ?string
    {
        return $this->Stato;
    }

    public function setStato(?string $Stato): self
    {
        $this->Stato = $Stato;

        return $this;
    }

    public function getCodiceFiscale(): ?string
    {
        return $this->CodiceFiscale;
    }

    public function setCodiceFiscale(?string $CodiceFiscale): self
    {
        $this->CodiceFiscale = $CodiceFiscale;

        return $this;
    }

    public function getTelefono1(): ?string
    {
        return $this->Telefono1;
    }

    public function setTelefono1(?string $Telefono1): self
    {
        $this->Telefono1 = $Telefono1;

        return $this;
    }

    public function getTelefono2(): ?string
    {
        return $this->Telefono2;
    }

    public function setTelefono2(?string $Telefono2): self
    {
        $this->Telefono2 = $Telefono2;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getCodiceUtente(): ?string
    {
        return $this->CodiceUtente;
    }

    public function setCodiceUtente(string $CodiceUtente): self
    {
        $this->CodiceUtente = $CodiceUtente;

        return $this;
    }

    public function getNota(): ?string
    {
        return $this->Nota;
    }

    public function setNota(?string $Nota): self
    {
        $this->Nota = $Nota;

        return $this;
    }

    public function getNota1(): ?string
    {
        return $this->Nota1;
    }

    public function setNota1(?string $Nota1): self
    {
        $this->Nota1 = $Nota1;

        return $this;
    }

    public function getNota2(): ?string
    {
        return $this->Nota2;
    }

    public function setNota2(?string $Nota2): self
    {
        $this->Nota2 = $Nota2;

        return $this;
    }

    public function getNota3(): ?string
    {
        return $this->Nota3;
    }

    public function setNota3(?string $Nota3): self
    {
        $this->Nota3 = $Nota3;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>

        <script type="text/javascript" src="{{ asset('assets/js/jquery-3.1.0.min.js') }}"></script>
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css">   
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/Datatables/datatables.min.css') }}"/>
        <script type="text/javascript" src="{{ asset('assets/Datatables/datatables.min.js') }}"></script>

        <meta charset="UTF-8">
        <title>{% block title %}MASO{% endblock %}</title>
        {% block stylesheets %}{% endblock %}

        <link rel="icon" type="image/x-icon" href="{{ asset('assets/images/favicon.ico') }}" />

    <script>
      // initialization and configuration
      $(document).ready( function () {
          $('#atable').dataTable( {
              "fixedHeader": true,
              "lengthMenu": [ 200, 100, 75, 50, 25, 10 ]
              //"info":     false, // remove header and footer 
              //"ordering": false, 
              //"bPaginate": false,
              //"sDom": 'T<"clear">lfrtip'
      	} ); // end dataTable
      } ); // end ready function
      // END initialization and configuration

      $(document).ready( function () {
          $('#btable').dataTable( {
              "fixedHeader": true,
              "lengthMenu": [ 200, 100, 75, 50, 25, 10 ]
              //"info":     false, // remove header and footer 
              //"ordering": false, 
              //"bPaginate": false,
              //"sDom": 'T<"clear">lfrtip'
      	} ); // end dataTable
      } ); // end ready function
      // END initialization and configuration

    </script>

  </head>
  <body>

    <div id="wrapper">
      <div align="left">
        <a href="{{ path('homepage') }}">
          <img src="{{ asset(logo_file) }}"
           alt="Logo-MASO"
           height="96" width="400"
           style="margin-left:20px;margin-right:20px;margin-top:20px;margin-bottom:20px;float:left">
        </a>
      </div>
    </div>

    <div align="right">
      {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        {% if userBelongsTo(users_admin, app.user.username) %} <font color="red">ADMIN</font> --- {% endif %}
        {% if userBelongsTo(users_manager, app.user.username) %} <font >MANAGER</font> --- {% endif %}
        User: {{ app.user.username }} ---
        <a href="{{ logout_path('main') }}">Logout</a>
      {% endif %}
    </div>

    
    {% block body %}{% endblock %}
    {% block javascripts %}{% endblock %}

    <hr>

    <center>
    <a href="https://github.com/giammy/maso" target="_blank">MASO</a> - 
    Progetto disponibile come "GNU General Public License v3.0" - <a href="http://giammy.com" target="_blank">Gianluca Moro</a>
    </center>

  </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  {% if userBelongsTo(users_admin, app.user.username) or
        userBelongsTo(users_manager, app.user.username) %}

    <center>
  
      <a href="{{ path('mostrapersona') }}">
          <img src="{{ asset('assets/images/icon-persone.svg') }}" 
	       alt="icon-persone" height="96" width="96"></a>
      <br>

      <a href="{{ path('modificapersona') }}">
          <img src="{{ asset('assets/images/icon-nuova-persona.svg') }}" 
	       alt="icon-nuova-persona" height="96" width="96"></a>

    </center>
      
  {% endif %}
	
{% endblock %}

templates/login.html.twig
{# template/login.html.twig #}
 
{% extends 'base.html.twig' %}
 
{% block body %}
  {% if error %}
    <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
  {% endif %}

  <script>
    function forceLower(strInput) {
      strInput.value=strInput.value.toLowerCase();
    }
  </script>
    
  <form action="{{ path('login') }}" method="post">
    <center>
      <table>
        <tr>
          <td><label for="username"><h2>Username:</h2></label></td>
          <td><input type="text" id="username" name="_username" 
                     value="{{ last_username }}" 
                     onkeyup="return forceLower(this);" 
                     style="text-transform: lowercase;"/></td>
        </tr>
        <tr>
          <td><label for="password"><h2>Password:</h2></label></td>
          <td><input type="password" id="password" name="_password" /></td>
        </tr>
        {#
          If you want to control the URL the user
          is redirected to on success (more details below)
          <input type="hidden" name="_target_path" value="/account" />
        #}
        <tr>
          <td></td>
          <td>
            <button type="submit" id="login-submit" class="button"
                    style="background-color: #0099bf; width: 120px">LOGIN</button></td>
        </tr>
      </table>
    </center>
  </form>
  {# <div align="right"> <b>Insert username and password</b> </div> #}
{% endblock %}
 
{% block stylesheets %}
{% endblock %}

templates/modificapersona.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifica persona{% endblock %}

{% block body %}

{{ form_start(form) }}

<table style="border-collapse: collapse;">
  <tr>
    <td> Cognome</td>
    <td> {{ form_widget(attribute(form, "cognome"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Nome</td>
    <td> {{ form_widget(attribute(form, "nome"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Soprannome</td>
    <td> {{ form_widget(attribute(form, "soprannome"), { 'attr': {'size': '40'} }) }} </td>
  </tr>

  <tr>
    <td> Indirizzo</td>
    <td> {{ form_widget(attribute(form, "indirizzo"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Citt&agrave;</td>
    <td> {{ form_widget(attribute(form, "citta"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Provincia</td>
    <td> {{ form_widget(attribute(form, "provincia"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Stato</td>
    <td> {{ form_widget(attribute(form, "stato"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Codice Fiscale</td>
    <td> {{ form_widget(attribute(form, "codiceFiscale"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Telefono1</td>
    <td> {{ form_widget(attribute(form, "telefono1"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Telefono2</td>
    <td> {{ form_widget(attribute(form, "telefono2"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> E-mail</td>
    <td> {{ form_widget(attribute(form, "email"), { 'attr': {'size': '40'} }) }} </td>
  </tr>
  <tr>
    <td> Nota</td>
    <td> {{ form_widget(attribute(form, "nota"), { 'attr': {'size': '40'} }) }} </td>
  </tr>

  
</table>


{{ form_end(form) }}

{% endblock %}

templates/mostrapersona.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mostra persone{% endblock %}

{% block javascripts %}
  <script>
    // initialization and configuration
    $(document).ready( function () {
        $('#personeShowallTable').dataTable( {
              "fixedHeader": true,
              "lengthMenu": [ 1000, 100, 75, 50, 25, 10 ]
              //"info":     false, // remove header and footer
              //"ordering": false,
              //"bPaginate": false,
              //"sDom": 'T<"clear">lfrtip'
        } ); // end dataTable
    } ); // end ready function
    // END initialization and configuration
  </script>
{% endblock %}


{% block body %}

<table id="personeShowallTable">
  <thead>
    <tr>
      <td></td>
      <td>Cognome</td>
      <td>Nome</td>
      {# <td>Soprannome</td> #}
      <td>Indirizzo</td>
      <td>Citt&agrave;</td>
      <td>Prov.</td>
      {# <td>Stato</td> #}
      <td>Codice Fiscale</td>
      <td>Telefono1</td>
      <td>Telefono2</td>
      <td>E-mail</td>
      <td></td>
      <td>Codice Utente</td>
      <td>Note</td>
    </tr>
  </thead>

  <tbody>
    {% for ar in list %}
    <tr>
      <td>        
        <a href="{{ path('modificapersona', { 'id': ar.id }) }}">
          <img src="{{ asset('assets/images/icon-edit.svg') }}" alt="edit" height="24" style="float:left"></img>
        </a>
      </td>
      <td> {{ ar.cognome }} </td>
      <td> {{ ar.nome }} </td>
      {# <td> {{ ar.soprannome }} </td> #}
      <td> {{ ar.indirizzo }} </td>
      <td> {{ ar.citta }} </td>
      <td> {{ ar.provincia }} </td>
      {# <td> {{ ar.stato }} </td> #}
      <td> {{ ar.codiceFiscale }} </td>
      <td> {{ ar.telefono1 }} </td>
      <td> {{ ar.telefono2 }} </td>
      <td> {{ ar.email }} </td>
      <td>

        <a href="{{ path('cancellapersona', { 'id': ar.id }) }}"
           onclick="return confirm('Rimuovo questo utente?')">
          <img src="{{ asset('assets/images/icon-delete.svg') }}" alt="delete" height="24" style="float:left"></img>
        </a>

      </td>
      <td> {{ ar.codiceUtente }} </td>
      <td> {{ ar.nota }} </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}